import { NetworkModeSchema } from "@payport/shared";
import { z } from "zod";

const PublicEnvSchema = z.object({
  NEXT_PUBLIC_API_URL: z.string().url().default("http://localhost:4000"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_PAYPORT_NETWORK_MODE: NetworkModeSchema.default("development"),
  NEXT_PUBLIC_ARBITRUM_ONE_SETTLEMENT_CONTRACT_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_ARBITRUM_SEPOLIA_SETTLEMENT_CONTRACT_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY: z.string().optional(),
  NEXT_PUBLIC_PARTICLE_PROJECT_ID: z.string().optional(),
  NEXT_PUBLIC_PARTICLE_CLIENT_KEY: z.string().optional(),
  NEXT_PUBLIC_PARTICLE_APP_UUID: z.string().optional()
});

export const publicEnv = PublicEnvSchema.parse({
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_PAYPORT_NETWORK_MODE: process.env.NEXT_PUBLIC_PAYPORT_NETWORK_MODE,
  NEXT_PUBLIC_ARBITRUM_ONE_SETTLEMENT_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_ARBITRUM_ONE_SETTLEMENT_CONTRACT_ADDRESS,
  NEXT_PUBLIC_ARBITRUM_SEPOLIA_SETTLEMENT_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_SETTLEMENT_CONTRACT_ADDRESS,
  NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY,
  NEXT_PUBLIC_PARTICLE_PROJECT_ID: process.env.NEXT_PUBLIC_PARTICLE_PROJECT_ID,
  NEXT_PUBLIC_PARTICLE_CLIENT_KEY: process.env.NEXT_PUBLIC_PARTICLE_CLIENT_KEY,
  NEXT_PUBLIC_PARTICLE_APP_UUID: process.env.NEXT_PUBLIC_PARTICLE_APP_UUID
});
